openapi: 3.0.0
info:
  title: todo-backend-api
  version: 0.0.2
paths:
  /todos:
    get:
      responses:
        "200":
          description: "ToDos"
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string
                    description: Description of what to do
                  completed:
                    type: boolean
                  order:
                    type: integer
                    format: int32
                  url:
                    type: string
                    format: uri
                required:
                  - title
                  - completed
                  - order
                  - url
            application/xml:
              example:
                title: "Mocked XML 1234 title"
                completed: true
                order: 13
                url: "http://mockedURL.com"
            text/plain:
              example: |
                title: "Mocked Text title"
                completed: true
                order: 13
                url: "http://mockedURL.com"
